"""Constants package for E-Kart backend."""

from constants.app_constants import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    DEFAULT_LIMIT,
    DEFAULT_PAGE,
    JWT_ALGORITHM,
    LOGIN_ATTEMPTS_LIMIT,
    LOGIN_ATTEMPTS_LOCKOUT_SECONDS,
    LOW_STOCK_THRESHOLD,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_OUT_FOR_DELIVERY,
    ORDER_STATUS_PROCESSING,
    ORDER_STATUS_SHIPPED,
    PASSWORD_RESET_EXPIRATION_MINUTES,
    RECENTLY_VIEWED_EXPIRE_SECONDS,
    RECENTLY_VIEWED_MAX_ITEMS,
    REDIS_CACHE_EXPIRE_SECONDS,
)

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "DEFAULT_LIMIT",
    "DEFAULT_PAGE",
    "JWT_ALGORITHM",
    "LOGIN_ATTEMPTS_LIMIT",
    "LOGIN_ATTEMPTS_LOCKOUT_SECONDS",
    "LOW_STOCK_THRESHOLD",
    "ORDER_STATUS_CANCELLED",
    "ORDER_STATUS_DELIVERED",
    "ORDER_STATUS_OUT_FOR_DELIVERY",
    "ORDER_STATUS_PROCESSING",
    "ORDER_STATUS_SHIPPED",
    "PASSWORD_RESET_EXPIRATION_MINUTES",
    "RECENTLY_VIEWED_EXPIRE_SECONDS",
    "RECENTLY_VIEWED_MAX_ITEMS",
    "REDIS_CACHE_EXPIRE_SECONDS",
]
