"""Application constant definitions for E-Kart backend."""

import os

# JWT & Authentication Constants
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
LOGIN_ATTEMPTS_LIMIT = 5
LOGIN_ATTEMPTS_LOCKOUT_SECONDS = 900
PASSWORD_RESET_EXPIRATION_MINUTES = 15

# Cache Constants
REDIS_CACHE_EXPIRE_SECONDS = 3600
RECENTLY_VIEWED_EXPIRE_SECONDS = 604800  # 7 days in seconds
RECENTLY_VIEWED_MAX_ITEMS = 10

# Inventory & Stock Constants
LOW_STOCK_THRESHOLD = int(os.getenv("LOW_STOCK_THRESHOLD", "5"))

# Order Statuses
ORDER_STATUS_PROCESSING = "PROCESSING"
ORDER_STATUS_SHIPPED = "SHIPPED"
ORDER_STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
ORDER_STATUS_DELIVERED = "DELIVERED"
ORDER_STATUS_CANCELLED = "CANCELLED"

# Default Pagination
DEFAULT_PAGE = 1
DEFAULT_LIMIT = 5
